In [ ]:
from __future__ import print_function

import os
import cv2
import numpy as np
np.random.seed(1337)
import sys

from keras.layers import Input
from keras_vggface.vggface import VGGFace

from vocabulary import Vocabulary

In [ ]:
 input_tensor = Input(shape=(224, 224, 3))
vgg_model = VGGFace(input_tensor=input_tensor, include_top=False, pooling='avg')

In [ ]:
vgg_model.summary()

In [ ]:
import numpy as np
data = np.load('da.npy')
print(data[-1])
print(data[-1].shape)

last = data[-1].reshape(1, 512)


print(last.shape)
print(last)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

In [ ]:
import numpy as np
np.random.seed(1337)

frames = np.ndarray(shape=(75, 224, 224, 3), dtype=np.float32)


In [ ]:
print(frames)

In [ ]:
import cv2
cap = cv2.VideoCapture('.\data\\videos\\s1\\bbaf2n.mpg')
print(cap)

In [ ]:
print (cap.read()[1].shape)

In [ ]:
t, img = cap.read()
x = cv2.resize(img, (224, 224)).astype(np.float32)
print(x.shape)

x = np.expand_dims(x, axis=0)
print(x.shape)
print(x)

In [ ]:
from PIL import Image
from matplotlib import pyplot as plt

import cv2
cap = cv2.VideoCapture('.\data\\videos\\s1\\bbaf2n.mpg')
t, img = cap.read()
cv2.imwrite("frame.jpg", img)   
    
img = mpimg.imread('./frame.jpg')
plt.imshow(img)
plt.show()

resized_frame = cv2.resize(img, (224, 224)).astype(np.float32)

resized_frame = np.expand_dims(resized_frame, axis=0)
# Zero-center by mean pixel
resized_frame[:, :, :, 0] -= 93.5940
resized_frame[:, :, :, 1] -= 104.7624
resized_frame[:, :, :, 2] -= 129.1863

cv2.imwrite("frame2.jpg", resized_frame[0])   
    
img = mpimg.imread('./frame2.jpg')
plt.imshow(img)
plt.show()


In [ ]:
plt.imshow(x[0])
plt.show()

In [ ]:
import matplotlib.image as mpimg
img = mpimg.imread('./slika.jpg')
    
plt.imshow(img)
plt.show()

In [ ]:
frames = np.ndarray(shape=(75, 224, 224, 3), dtype=np.float32)


t, img = cap.read()

resized_frame = cv2.resize(img, (224, 224)).astype(np.float32)
print('daaa')
print(resized_frame.shape)
resized_frame = np.expand_dims(resized_frame, axis=0)
print(resized_frame.shape)

# Zero-center by mean pixel
resized_frame[:, :, :, 0] -= 93.5940
resized_frame[:, :, :, 1] -= 104.7624
resized_frame[:, :, :, 2] -= 129.1863
frames[1,:,:,:] = resized_frame
frames[2,:,:,:] = resized_frame
frames[3,:,:,:] = resized_frame    

word_frames = []
word_frames.append(frames[1:3,:,:])
word_frames.append(frames[2:3,:,:])
len(word_frames)

In [ ]:
a = []
b = [[1], [2], [3], [4], [5]]
print(b[1:4])

In [ ]:
a = []
a.append(b[1:4])
a.append(b[4:5])
print(a)

In [ ]:
a = [1,2,4,5]
a[1:3]

In [ ]:
frames = np.zeros(shape=(3,3), dtype=np.float32)

print(frames)
print(frames.shape)
frames = np.expand_dims(frames, axis=0)
print(frames)
print(frames.shape)

In [ ]:
a = [1,3,4]
b = [0]
b[0] = a
a[0] = 100
print(b)

In [156]:
a = np.zeros(shape=(3,3), dtype=np.float32)

In [157]:
a[0] = [1,2,4]
print(a)

[[1. 2. 4.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [158]:
b = np.zeros(shape=(1,3,3), dtype=np.float32)
b[0] = a

In [159]:
print(b)

[[[1. 2. 4.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [160]:
a[0] = [9,9,0]
print(b)

[[[1. 2. 4.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [161]:
print(a)

[[9. 9. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [152]:
b[0,:,:] = a

In [163]:
print(b)

[[[1. 2. 4.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [162]:
a =  np.expand_dims(a, axis=0)
print(a)

[[[9. 9. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [164]:
b[0,:,:] = a
print(b)

[[[9. 9. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
